name: Docker Image CI

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
            cd Pass-List-App
            docker build . --file dockerFile_2 --tag students.azurecr.io/nodejs-app-ygh:$(date +%s)
    - name: Verificar imagen
      run: docker images
    - name: Push Image to ACR
      uses: julioarruda/pushimagetoregistry@v1
      with:
        acr-tokenname: ${{ secrets.TOKEN_NAME }}
        acr-token: ${{ secrets.ACR_TOKEN_VALUE }}
        acr-account: students.azurecr.io
        acr-imagename: students.azurecr.io/nodejs-app-ygh:$(date +%s)
