name: analizador de datos 

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permite ejecutar el workflow manualmente

jobs:
  analyze-scripts:
    runs-on: ubuntu-latest #ambiente donde va a correr el aplicativo
    steps: 
       - name: checkout code #extración del código (la maquina virtual no tiene acceso al código)
         uses: actions/checkout@v3 #workflows independientes y lo referenciamos
        
       - name: check files
         run: ls 

              
